<div class="grid-container">
    <div class="grid-100" style="margin-bottom:30px;">
        <div style="width:100%;height:300px;background:url(/img/contacto-header.png) no-repeat;"></div>
    </div>
    <div class="clear"></div>
    <div class="grid-25 row push-15">
        <img src="/img/map.png"/>
    </div>
    <div class="grid-40 row push-20">
        <h1>Lorem ipsum dolor sit amet</h1>
        <strong>Donec vestibulum pellentesque magna sit amet faucibus. 
        In auctor lobortis commodo. Fusce non feugiat mauris, vitae volutpat sem. 
        Suspendisse et faucibus lectus, quis imperdiet dolor.</strong>
        <p>
        Av Corrientes 1066<br/>
        Argentina<br/>
        Buenos Aires<br/>
        3456
        </p>
    </div>
</div>