<div class="grid-80 push-10">
    <h1>Listo!</h1>
</div>
<div class="grid-80 push-10">
    <p>Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. 
    Quisque egestas, eros id convallis aliquam, lacus odio dictum mauris, in eleifend purus est in erat. 
    Integer ut hendrerit tortor. Quisque velit massa, dictum ut consequat ultricies, sodales at turpis. 
    Vivamus euismod, eros ac consectetur bibendum, metus mi aliquam arcu, ut condimentum arcu nunc id eros. 
    Nunc fringilla, nibh nec dapibus tempus, dolor ligula dignissim felis, fermentum tristique ipsum elit sed ante.</p>
    <br/>
    <a href="./download-booking" class="button">Download PDF</a><br/><br/>
    <a href="/index/home" class="button">Home</a>
</div>