<script type="text/javascript" src="/js/jquery.js"></script>
</script>
<div class="grid-45 push-10 landingPage">
    <h1>Soluciones gastonómicas en 4 pasos.</h1>
    <h2>¡LA CALIDAD DE SIEMPRE, AHORA MUCHO MÁS FACIL!</h2>
    <a class="button" href="/elegi-el-servico">CLICK AQUÍ PARA EMPEZAR</a>
</div>
<div class="grid-40 push-10">
    <div class="home-picture" style="background:url(/img/home-combo-image.jpg) no-repeat;">
        <img src="/img/home-combo-border.png" />
    </div>
    <div class="home-picture-message-image">
    </div>
    <div class="home-picture-message">
        PROMO DESAYUNDO 50% OFF!
    </div>
</div>