<script type="text/javascript" src="/js/jquery.js"></script>
<script type="text/javascript" src="/js/bootstrap.tooltip.min.js"></script>
<script type="text/javascript" src="/js/order.js"></script>
<script type="text/javascript" src="/js/personalizar.js"></script>
<script type="text/javascript">
$(document).ready(function()
{
    //When the user lands on the personal product selection page, check the selected products
    if (isOnPersonalProductSelectionPage())
    {
        checkSelectedPersonalProducts();
    }

    var comboId = $("#comboId").val();
    var size = $("#size").val();
    var guests = $("#guests").val();
    var waiters = $("#waiters").val();

    getOrderOptions(comboId, size, guests, waiters, function(options)
    {
        var order = new Order(options);

        //populate inputs
        order.populatePersonalizeInputs();

        //validate guest input
        order.validateGuestInput();

        //validate waiter input
        order.validateWaiterInput(function(order)
        {
            //save params
            order.saveOrderParams(function(order)
            {
                //update the totals in the gui
                order.updateTotals();
            });
        });
        
        //react to change of guest
        $('#guests').bind('change', function()
        {
            self = order;
            self.validateGuestInput();
            self.validateWaiterInput(function(self){
                self.saveOrderParams();
            });
            
        });

        //When the user clicks on an input, handle accordingly
        $('input[type="checkbox"]').bind('click', function()
        {
            //save the selection
            savePersonalProductSelection(order, comboId, size, function(order)
            {
                //update the total of the order
                order.updateOrderTotalWithPersonalProducts(comboId, size, function(order)
                {
                    //redirect to personalize page if not on it already
                    if (isOnPersonalProductSelectionPage() === false)
                    {
                        var comboId = $("#comboId").val();
                        window.location.href = "/elegi-el-servico/personalizar?comboId=" + comboId + "&size=personal";
                    } else {
                      //update the totals in the gui
                      order.updateTotals();
                    }
                });
            });
        });

        
    });

    //Bind the buttons with tooltips
    $(".tip").bind('mouseenter', function(){
        $(this).tooltip('show');
    });
});
</script>
<div class="grid-65 push-5">

    <input type="hidden" class="order-input" id="comboId" name="comboId" value="<?php echo $this->combo->getId(); ?>" />
    <input type="hidden" class="order-input" id="size" name="size" value="<?php echo $this->size; ?>" />
    <input type="hidden" class="order-input" id="minimimGuests" value="<?php echo $this->combo->getMinimimGuests(); ?>" />
    <input type="hidden" class="order-input" id="guestsPerWaiter" value="<?php echo $this->combo->getGuestsPerWaiter(); ?>" />
    <input type="hidden" class="order-input" id="waiters" value="<?php echo $this->combo->getMinimumWaiters(); ?>" />
    <input type="hidden" class="order-input" id="discount" value="<?php echo $this->combo->getDiscount($this->size); ?>" />
    <input type="hidden" class="order-input" id="tax" value="<?php echo $this->combo->getTax(); ?>" />
    
    <div class="grid-50 combo-title">
        <h1>Servico Personalizado</h1>
        <label>SELECCIONE LOS PLATOS DE SU PREFERENCIA</label>
    </div>

    <div class="grid-50 combo-top-filters">

        <h1>Servicos Prearmados</h1>

        <ul class="combo-filter">
            <?php foreach($this->combos as $combo): ?>
                <li>
                    <a class="button combo-name <?php echo ($combo->getId() == $this->combo->getId()) ? 'active' : null; ?>" href="/elegi-el-servico/personalizar?comboId=<?php echo $combo->getId(); ?>&size=full"><?php echo $combo->getName(); ?></a>
                    <ul class="combo-filter-sizes">
                        <li><a class="tip button <?php echo ($this->size == 'basico' && $combo->getId() == $this->combo->getId()) ? 'active' : null; ?>" href="/elegi-el-servico/personalizar?comboId=<?php echo $combo->getId(); ?>&size=basico" data-toggle="tooltip" title="Basico">B</a></li>
                        <li><a class="tip button <?php echo ($this->size == 'medio' && $combo->getId() == $this->combo->getId()) ? 'active' : null; ?>" href="/elegi-el-servico/personalizar?comboId=<?php echo $combo->getId(); ?>&size=medio" data-toggle="tooltip" title="Medio">M</a></li>
                        <li><a class="tip button <?php echo ($this->size == 'full' && $combo->getId() == $this->combo->getId()) ? 'active' : null; ?>" href="/elegi-el-servico/personalizar?comboId=<?php echo $combo->getId(); ?>&size=full" data-toggle="tooltip" title="Full">F</a></li>
                        <li>
                            <a href="/elegi-el-servico/personalizar?comboId=<?php echo $combo->getId(); ?>&size=personal"
                               class="tip button 
                                      <?php echo ($this->isPersonalTabInActive($this, $combo)) ? 'inactive' : null; ?>
                                      <?php echo ($this->isPersonalTabActive($this, $combo)) ? 'active' : null; ?>"
                               onclick="<?php echo ($this->isPersonalTabInActive($this, $combo)) ? 'return false;' : null; ?>" 
                               data-toggle="tooltip" title="Personal"
                            >P</a>
                        </li>
                    </ul>
                </li>
                <li class="delimeter"></li>
            <?php endforeach ?>
        </ul>

    </div>

    <div class="grid-100 combo-products">

        <?php foreach ($this->products as $categoryId => $groups): ?>

            <div class="category">

                <h1><?php echo $this->categories[$categoryId]->getName(); ?></h1>

                <?php foreach($groups as $groupId => $products): ?>

                    <div class="group">

                        <h1><?php echo $this->groups[$groupId]->getName(); ?></h1>

                        <ul>
                            <?php foreach ($products as $product): ?>
                                <?php $isEnabled = in_array($categoryId, $this->combo->getActiveCategoriesBySizeId($this->size)); ?>
                                <li>
                                    <input
                                        data="<?php echo $product->getId(); ?>"
                                        type="checkbox"
                                        <?php echo (in_array($product->getId(), $this->combo->getSelectedProductIdsBySizeId($this->size))) ? 'checked' : null ; ?>
                                        <?php echo ($isEnabled ) ? 'enabled' : 'disabled'; ?>
                                    />
                                    <span style="color:<?php echo ($isEnabled) ? 'black' : 'grey'; ?>;"><?php echo $product->getName(); ?></span>
                                </li>
                            <?php endforeach ?>
                        </ul>

                    </div>

                <?php endforeach ?>

            </div>

        <?php endforeach ?>

    </div>

</div>

<div class="grid-25 push-5">

    <div class="grid-100 combo-right-filters">

        <img src="/img/combo-right-filter-image.png" width="100%"/>

        <form action="" method="post">

            <div class="row">
                <label>
                    INVITADOS:&nbsp;
                    <input style="width:45px;padding:5px;" class="order-input" id="guests" type="text" value="<?php echo $this->order->getGuests(); ?>"/>
                </label>
            </div>
            
            <div class="row">
                <label>
                    TOTAL:&nbsp;
                    <input style="width:95px;padding:5px;" id="total" type="text" value="<?php echo $this->order->getTotal();?>" disabled/>
                </label>
            </div>

            <div class="row">
                <label>
                    $/pers:&nbsp;
                    <input style="width:95px;padding:5px;" id="pricePerPerson" type="text" value="<?php echo $this->order->getPricePerPerson();?>" disabled/>
                </label>
            </div>
            
            <a class="button" href="/customizalo-a-tu-medida?comboId=<?php echo $this->combo->getId();?>&size=<?php echo $this->size; ?>">PRESUPUESTAR</a>

        </form>

    </div>

</div>