<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>LANCH</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="stylesheet" href="/css/unsemantic-grid-base.css" />
        <link rel="stylesheet" href="/css/unsemantic-grid-responsive.css" />
        <link rel="stylesheet" href="/css/front.css" />
        <link rel="stylesheet" href="/css/fonts.css" />
        <link rel="stylesheet" href="/css/ui-darkness/jquery-ui.datepicker.min.css" />
        <link rel="stylesheet" href="/css/bootstrap.tooltip.min.css" />
        <link href='http://fonts.googleapis.com/css?family=Raleway:800' rel='stylesheet' type='text/css'>
        <link href='http://fonts.googleapis.com/css?family=Bowlby+One' rel='stylesheet' type='text/css'>
    </head>
<body> 
    <div class="grid-container">
        <div class="grid-15 logo">
            <a href="/index/home"><img src="/img/logo.gif" height="90"/></a>
        </div>
        <div class="grid-85 menu">
            <?php echo $this->partial('elements/menu.phtml'); ?>
        </div>
    </div>
    
    <div class="grid-container">
        <?php echo $this->layout()->content ?> 
    </div>

    <div class="grid-container steps">
        <?php echo $this->partial('elements/step-counter.phtml'); ?>
    </div>
    
    <!-- Google Analytics -->
    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
        
        ga('create', 'UA-43763133-1', 'lanch.com.ar');
        ga('send', 'pageview');
    </script>
</body>
</html>