<?php echo $this->doctype() ?>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>LANCH</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <link href="/css/bootstrap.css" rel="stylesheet">
    <link href="/css/admin.css" rel="stylesheet">
    <link href="/css/bootstrap-responsive.css" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
    
    <div class="container">
      <?php echo $this->layout()->content ?>
    </div>

    <script src="../js/jquery.js"></script>
    <script src="../js/bootstrap.js"></script>

  </body>
</html>