<h2>Nuevo Armado</h2>

<?php if(!empty($_POST) && !empty($this->messages)): ?>
    <?php foreach ($this->messages as $key => $messages): ?>
        <?php foreach ($messages as $message): ?>
            <div class="alert alert-error">
              <button type="button" class="close" data-dismiss="alert">&times;</button>
              <?php echo $message; ?>
            </div>
        <?php endforeach ?>
    <?php endforeach ?>
<?php endif ?>

<form class="form-vertical" action="" method="post" enctype="multipart/form-data">

    <div class="row">
        <div class="span4">

            <div class="control-group">
                <div class="controls">
                    <a class="btn btn-success" href="/admin/combos">
                        <i class="icon-arrow-left icon-white"></i>
                    </a>
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="name">Nombre</label>
                <div class="controls">
                  <input type="text" name="name" id="name">
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="base_price">Precio Base</label>
                <div class="controls">
                    <div class="input-prepend input-append">
                        <span class="add-on">$</span>
                        <input class="span1" id="appendedPrependedInput" type="text" name="base_price" id="base_price">
                        <span class="add-on">.00</span>
                    </div>
                </div>
            </div>
            
            <div class="control-group">
                <label class="control-label" for="base_price">Descuento Armado</label>
                <div class="controls">
                    <div class="input-prepend">
                        <span class="add-on">%</span>
                        <input class="span1" id="prependedInput" type="text" name="discount" id="discount">
                    </div>
                </div>
            </div>
            
            <div class="control-group">
                <label class="control-label" for="base_price">Invitados Minimo</label>
                <div class="controls">
                    <div class="input">
                        <input class="span1" type="text" name="minimum_guests" id="minimum_guests">
                    </div>
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="base_price">Imagen</label>
                <div class="controls">
                    <div class="fileupload fileupload-new" data-provides="fileupload">
                      <div class="input-append">
                        <div class="uneditable-input span3"><i class="icon-file fileupload-exists"></i> <span class="fileupload-preview"></span></div><span class="btn btn-file"><span class="fileupload-new">Select File</span><span class="fileupload-exists">Change</span><input type="file" name="image"/></span>
                      </div>
                    </div>
                </div>
            </div>

            <div class="control-group">
                <div class="controls">
                    <input class="btn btn-primary" type="submit" value="Guardar" />
                </div>
            </div>
        </div>
    </div> 

</form>