<h2>Categorías</h2>

<a href="/admin/add-category" class="btn btn-success" style="margin:5px 0 15px 0;"><i class="icon-plus icon-white"></i> Nuevo Categoría</a>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->categories as $category): ?>
        <tr>
            <td><?php echo $category->getName(); ?></td>
            <td>
                <div class="btn-group">
                  <a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="icon-tasks icon-white"></i>
                    <span class="caret"></span>
                  </a>
                  <ul class="dropdown-menu">
                    <li><a href="/admin/edit-category?categoryId=<?php echo $category->getId(); ?>"><i class="icon-pencil"></i> Editar</a></li>
                    <li><a href="/admin/delete-category?categoryId=<?php echo $category->getId(); ?>" onclick="return confirm('Are you sure you want to delete this category?')"><i class="icon-trash"></i> Borrar</a></li>
                  </ul>
                </div>
            </td>
        </tr>
        <?php endforeach ?>
    </tbody>
</table>