<h2>Armados</h2>

<a href="/admin/add-combo" class="btn btn-success" style="margin:5px 0 15px 0;"><i class="icon-plus icon-white"></i> Nuevo Armado</a>
<br/> 
<table class="table table-striped">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Precio Base</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->combos as $combo): ?>
        <tr>
            <td><?php echo $combo->getName(); ?></td>
            <td>$<?php echo $combo->getBasePrice(); ?></td>
            <td>
                <div class="btn-group">
                  <a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="icon-tasks icon-white"></i>
                    <span class="caret"></span>
                  </a>
                  <ul class="dropdown-menu">
                    <li><a href="/admin/edit-combo?comboId=<?php echo $combo->getId(); ?>"><i class="icon-pencil"></i> Editar</a></li>
                    <li><a href="/admin/delete-combo?comboId=<?php echo $combo->getId(); ?>" onclick="return confirm('Are you sure you want to delete this combo?')"><i class="icon-trash"></i> Borrar</a></li>
                  </ul>
                </div>
            </td>
        </tr>
        <?php endforeach ?>
    </tbody>
</table>