<h2>Facturas</h2>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Numero</th>
            <th>Empresa</th>
            <th>Invitados</th>
            <th>Total</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->unseenBookings as $booking): ?>
        <tr>
            <td>#<?php echo $booking->getId(); ?></td>
            <td><?php echo $booking->getCompanyName(); ?></td>
            <td><?php echo $booking->getGuests(); ?></td>
            <td><?php echo $booking->getTotal(); ?></td>
            <td>
                <div class="btn-group">
                  <a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="icon-tasks icon-white"></i>
                    <span class="caret"></span>
                  </a>
                  <ul class="dropdown-menu">
                    <li><a href="/admin/edit-invoice?invoiceId=<?php echo $booking->getId(); ?>"><i class="icon-pencil"></i> Ver</a></li>
                  </ul>
                </div>
            </td>
        </tr>
        <?php endforeach ?>
    </tbody>
</table>